### ISSUE TITLE
[Guidance & Control] ros2_control for maritime robotics

### ISSUE THREAD

**Issue by destogl** [ros-maritime/issue_tracking#21]
I am currently working on the control of ROV using ros2_control. The components from the image below will be open-source.

![water_robots_ros2_control_architecture](https://user-images.githubusercontent.com/1918204/174607545-76c1a357-ae94-4d83-939b-027ba3faea87.png)

There could be potential overlap with #9 because we have TAM controller that does this, but currently only from data in a yaml file.

### Tasks

- [ ] thruster controller
- [ ] TAM controller
- [ ] velocity controller for ROVs (maybe compatible with other maritime robots)
- [ ] position control (basically PID controller)
- [x] start discussion about simulation in Gazebo to enable it (@arjo129 we have to make a meeting about this)

**Comment by oKermorgant** [comment]
Hi, 

The `thruster_manager` package we use is here: https://github.com/CentraleNantesROV/thruster_manager

It can be used as an actual node, or as a pure computing library to be embedded in another high-level control node.

I guess the interesting part lies in https://github.com/CentraleNantesROV/thruster_manager/blob/main/src/model_parser.h
This is where the TAM is build automagically from the thruster joints. They can be specified with 3 ways:
- an explicit list of joints
- a prefix for all joint names
- or let the code find which joints have a corresponding Ignition thruster plugin

**Comment by bartboogmans** [comment]
I have two questions on this project line:
1.  Does this project aim to (collaboratively) formulate a general use/benchmark vessel motion controller, or is this a design for a particular usecase that is partly shared to help other developers?
2. I see the maritime industry adopting automation as variations of dynamical positioning or heading control systems. Rarely do people have approaches to close the gap between operating zones. What kind of operating conditions is this controller designed for in terms of typical velocities? e.g.:
- It's supposed to be an all round framework for all speeds
- Low velocity operation (e.g. alike classical vessel Dynamical Positioning systems)
- High velocity operation (e.g. classical heading and surge speed control)

**Comment by konczg** [comment]
Hi @destogl @oKermorgant 
Are the ROS2 control components still being planned to be open sourced? Or if they are already, could you please tell where can they be accessed?
We have seen that there is a https://github.com/CentraleNantesROV/auv_control repository, referred to by https://github.com/CentraleNantesROV/bluerov2, but that seems to be unavailable. Is there any information regarding that repository?
@kisg

**Comment by oKermorgant** [comment]
Hi, indeed it was private and this was probably an error.
I have just set it public, it will remain open source and above all open to contributions.

**Comment by konczg** [comment]
@oKermorgant Thanks!

**Comment by jeskesen** [comment]
Hello, I was going to write something exactly like this myself, so I'd be happy to contribute to this effort instead.  

Here was what I had been thinking:
- My "TAM Controller" was simply going to be "Effort Controller" taking a WrenchStamped (so the reference frame to apply forces & torques) and outputs an effort command interface to each thruster.  @oKermorgant , your [thruster manager](https://github.com/CentraleNantesROV/thruster_manager) is pretty much exactly what I envisioned, except it would get the thruster locations from /tf, and it would inherit from a chainable ROS2 controller.
- The hardware interfaces for the thrusters would convert requested thrust forces from the TAM/effort controller, and run through a model to map that into a command.
    - The hardware interfaces would be admittedly complicated, since the model would encompass both the ESC and the thruster itself, as well as the actual hardware interface (like the pca9685 for generating the PWM outputs).  Perhaps even taking in a measured battery voltage.
    - As an example, model a BlueRobotics T200 thruster using a BasicESC by using their [perfomance charts](https://bluerobotics.com/store/thrusters/t100-t200-thrusters/t200-thruster-r2-rp/#tab-technical-details).   The actual IO to the ESC can be accomplished via the pca9685 chip, pwm_gpio, etc. 
    
I guess to summarize, I'd like to help & to get started.  Is there already a work in progress?

**Comment by oKermorgant** [comment]
Hi,

Indeed the `thruster_manager` we have chosen not to rely on `/tf` but parse the model instead. This was done to avoid instantiating a `tf listener` to get thrusters locations that are probably constant. This could easily be added as an option, feel free to submit a PR.

Similarly, I am not familiar with ROS 2 controllers and the thruster manager is really just a kind of bridge that changes a wrench to thruster forces. It can be used as an independent node or as a function that is used by another one (e.g. higher-level controller as in  [auv_control](https://github.com/CentraleNantesROV/auv_control/blob/b6e1419b4bc381ef250da3aab94da96f8918205c/include/auv_control/controller_io.h#L135).

Note that in [another package](https://github.com/CentraleNantesROV/blurr), that is related to the actual hardware, we subscribe to thruster forces (output by `thruster_manager` and change it to PWM according to our autopilot (Navio2) with all the details on PWM, pins, and so on.

**Comment by mabelzhang** [comment]
For book-keeping, @evan-palmer is working on https://github.com/Robotic-Decision-Making-Lab/blue/issues/33

**Comment by bartboogmans** [comment]
@jeskesen To add to the discussion of the TAM, I think that there is not 1 way to solve the thrust allocation problem, as there are a wide variety of complexities possible in this type of module. There is a time and place for solutions with different complexities/performances/priorities. 

What would be nice, is having a standard on how this TAM interfaces with a vessel/actuator description and other nodes, such that different modules can be interchanged. Has anyone ever encountered such standards? (maybe this discussion deserves it's own thread, though)

As far as I could quickly judge, [the mentioned TAM](https://github.com/CentraleNantesROV/thruster_manager) does purely what one would expect from this subsystem, whilst using urdf. I think it's a great starting point.

**Comment by bartboogmans** [comment]
Also: do the devs have an answer to this [previous question](https://github.com/ros-maritime/issue_tracking/issues/21#issuecomment-1340715719)?

**Comment by jeskesen** [comment]
@bartboogmans, I 100% agree that there is more than 1 way to solve this.  I would love it if I could align with a group consensus so that we could work collaboratively on this effort.   First of all, I acknowledge the very concept of "thruster allocation" implies an assumption that you are controlled by thrusters on the various axes... which may not be true for torpedo-style AUVs which use fins to control pitch & yaw.  However, it happens to suit my particular use case (for a holonomic, thruster driven, hovering ROV/AUV), but I understand it isn't applicable to everyone. 

I have tried out [thruster manager](https://github.com/CentraleNantesROV/thruster_manager), and it seems to be working for what I'd like it to do.  I think it would just need to be refactored into a ROS2 controller in order to make it suitable for this effort (as I understand it).

**Comment by oKermorgant** [comment]
Hi,

`thruster_manager` was written as a core capability that should be used from other tools.
In [auv_control](https://github.com/CentraleNantesROV/auv_control) it is used as an external dependency to embed TAM inside higher-level control nodes. Such nodes typically compute a desired wrench and then just call TAM to get the corresponding thruster forces.

My guess is that it can be a dependency to another package that would rely on ROS 2 control.

Finally, there is indeed a limitation when one uses fins. To my point of view it should be another tool that manages the allocation for such ROVs / AUVs as the underlying modeling is pretty different.

**Comment by jeskesen** [comment]
@oKermorgant , the very small change I think is necessary only comes down to some details of the implementation within your ThrusterManager class .  ThrusterManager gets its params, etc by passing in a Node object, which it then uses to get parameters, log messages. etc.  A controller, which inherits from ControllerInterface will have access to a Lifecycle Node ([here](https://github.com/ros-controls/ros2_control/blob/0863acd6905af0eba4db1074f11edd60215758d5/controller_interface/src/controller_interface_base.cpp#L114)).  Since it doesn't appear to me (and I may be wrong...) that Nodes and LifecycleNodes share a common ancestor through inheritance, I don't think polymorphism will come to the rescue here.

**Comment by oKermorgant** [comment]
@jeskesen I have [made the functions template](https://github.com/CentraleNantesROV/thruster_manager/blob/b0cc96a9b668c01807a9ed37898cbf645ebd293d/include/thruster_manager/thruster_manager.h#L37) so that they can adapt to the indeed absence of polymorphism between a Node and a LifecycleNode. 

I am not  an expert on Lifecycle nodes though and am willing to get feedback on whether this approach is enough.

**Comment by evan-palmer** [comment]
Hey folks, I wanted to share that we put together [auv_controllers](https://github.com/Robotic-Decision-Making-Lab/auv_controllers) to close https://github.com/Robotic-Decision-Making-Lab/blue/issues/33. The project has some overlap with what was discussed and proposed in this issue. It's worth noting that auv_controllers is intended for ROV-style vehicles like the BlueROV2 (it might work with other vehicles like gliders, but I haven't tried). I'm hoping to add some additional controllers in the future like MPC and a first or second order thruster model. We also implemented [hydrodynamics](https://github.com/Robotic-Decision-Making-Lab/hydrodynamics) to support dynamic controllers, and I'm hoping to extend that in the future to support parsing parameters from a URDF and eventually support manipulators and UVMS.
